default:
    trainer: ppo
    use_curiosity: true
    batch_size: 128
    beta: 1.0e-2
    buffer_size: 2048
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 1.0e6
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 128
    sequence_length: 64
    summary_freq: 5000
    use_recurrent: false
    vis_encode_type: simple
    pretraining:
        demo_path: ./demos/BarbarianDemo3.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: demos/BarbarianDemo3.demo
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
