default:
    trainer: ppo
    use_curiosity: true
    batch_size: 32
    beta: 1.0e-2
    buffer_size: 2048
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 2.0e-4
    learning_rate_schedule: linear
    max_steps: 3.0e7
    memory_size: 256
    normalize: true
    num_epoch: 5
    num_layers: 3
    time_horizon: 128
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    behavioral_cloning:
        demo_path: demos/Barbarian.demo
        strength: 0.4
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: demos/Barbarian.demo
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
